### PR TITLE
Migrated for Grunt v0.4.0

### PR DESCRIPTION
**Pull request by martin-naumann**
- Moved files to appropriate folders
- Changed template.js to use the latest API

### CODE REVIEW

**Comment by devgeeks** [comment]
I am the worst ever. Sorry this took so long.

**Comment by martin-naumann** [comment]
Haha, don't worry. Sometimes it takes me much longer to react to PRs ;-)
It's no big deal!

On Wed, Apr 17, 2013 at 11:38 AM, tommy-carlos williams <
notifications@github.com> wrote:

> I am the worst ever. Sorry this took so long.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/devgeeks/grunt-init-cordova/pull/1#issuecomment-16496220
> .

## 

Martin Naumann | Technology Expert R&D | Centralway Incubator

**Comment by devgeeks** [comment]
This is a big ask since I took so long to get to this (I still haven't migrated off Grunt 0.3.x :/ So I was holding off a bit).

Could you take a look at the README and fix it for Grunt 0.4.x?

For example, the way you install grunt now is different and I don't even know how you install 0.4.x init stuff yet myself.

**Comment by martin-naumann** [comment]
Sure. Gimme some time, maybe I come around to that this evening

On Wed, Apr 17, 2013 at 11:42 AM, tommy-carlos williams <
notifications@github.com> wrote:

> This is a big ask since I took so long to get to this (I still haven't
> migrated off Grunt 0.3.x :/ So I was holding off a bit).
> 
> Could you take a look at the README and fix it for Grunt 0.4.x?
> 
> For example, the way you install grunt now is different and I don't even
> know how you install 0.4.x init stuff yet myself.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/devgeeks/grunt-init-cordova/pull/1#issuecomment-16496360
> .

## 

Martin Naumann | Technology Expert R&D | Centralway Incubator

**Pull request merged**
